print(33>22)
print(33<22)
print(33<=22)
print(33>=22)
print(33==22)
print(33!=22)
print("-----------------")

print(True and True)
print(True and False)
print(False and True)
print(False and False)

print("-----------------")
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print("-----------------")
print(bool(0))
print(bool(1))
print(bool(''))
print(bool("hello"))
print(bool(None))


